server:
  port: 8760		  
spring:
  application:
    name: service-gateway	
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/		    
zuul:
  routes:
    users:
      path: /provider/**
      serviceId: service-provider  #http://localhost:8760/provider/provider/get?name=sunbin
    consumer:
      path: /consumer/**  #这里的配置表示，访问/producer/** 直接重定向到http://域名/**
      url: http://localhost:8763/consumer/	#http://localhost:8760/consumer/get?name=sunbin